[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "drug-solubilitoo"
version = "0.1.0"
description = "Drug Solubility Analysis Tool"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.2",
]

[tool.setuptools]
py-modules = ["main", "datacleaner"]
